name: Update Status Of GitHub Projects Beta Items
description: Update Status Of GitHub Projects Beta Items
author: GitHub
branding:
  icon: table
inputs:
  project-url:
    required: true
    description: URL of the project to add issues to
  github-token:
    required: true
    description: A GitHub personal access token with write access to the project
  labeled:
    required: false
    description: A comma-separated list of labels to use as a filter for issue to be added
  status:
    required: true
    description: The status that matching issues will be updated to
runs:
  using: 'node16'
  main: 'dist/index.js'
